# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.2"
manifest_format = "2.0"
project_hash = "b138e4141deea5c05b9f58626696400b6266dd2e"

[[deps.Random]]
deps = ["SHA"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
version = "1.11.0"

[[deps.SEQ2EXPdata]]
deps = ["Random"]
path = "."
uuid = "321b9d11-aa10-4af3-aaad-5d74081bdd4f"
version = "1.0.7"

[[deps.SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"
version = "0.7.0"
