name = "SEQ2EXPdata"
uuid = "321b9d11-aa10-4af3-aaad-5d74081bdd4f"
authors = ["Shane Kuei-Hsien Chu (skchu@wustl.edu)"]
version = "1.0.8"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1.11.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
